### ISSUE TITLE
Add CONTRIBUTING.md and CODE_OF_CONDUCT.md file

### ISSUE THREAD

**Issue by theritikchoure** [maddhruv/github-readme-npm-downloads#5]
Add two files -

- CONTRIBUTING.md
- CODE_OF_CONDUCT.md

**Comment by maddhruv** [comment]
Hey @theritikchoure 
This repository is not supposed to invite any contributions, that's why I don't have a cotributing markdown, but if you are looking to something to get started with this repo, checkout - https://github.com/maddhruv/github-readme-npm-downloads/blob/master/GET_STARTED.md

The same applies for code of conduct as well
